matrix_bot_user : "@bot:example.com"

talks_server : "127.0.0.1"
talks_port : 8080
talks_protocol : "http"
talks_receive_message : "/matrix/receiveMessage"
talks_get_messages : "/matrix/getMessages"
talks_confirm_messages : "/matrix/confirmMessages"
talks_tag_room : "/matrix/tagRoom"

bot_on_regex : '.*Continue.*'
bot_off_regex : '.*Hola!.*'

hints : true

room_tags:
  - regex : '.*end user.*'
    tag : "profile"
    value : "end_user"
  - regex : '.*service provider.*'
    tag : "profile"
    value : "service_provider"

deduplication_cache_size : 1024
echo_cache_size : 1024
fixed_timeout : 3.05
message_fetcher_delay : 0.2
message_propagator_delay : 0.5
hints_delay : 1.0

talks_api_key : "TALKS_API_KEY"
